apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}

techtrends-staging
3 minutes
Service
svc
techtrends
13 minutes
Deployment
deploy
techtrends
13 minutesRev:2
Pod
pod
techtrends-54d444f688-mdhpm
11 minutesCrashLoopBackOff0/16
Pod
pod
techtrends-686f4cbff7-bnqts
13 minutesImagePullBackOff0/1
Pod
pod
techtrends-686f4cbff7-nqtjj
13 minutesImagePullBackOff0/1
Pod
pod
techtrends-686f4cbff7-x4tv5
13 minutesImagePullBackOff0/1
clear filters to show 5 additional resources
        name: techtrends
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbePath }}
            port: 3111
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbePath }}
            port: 3111