namespace:
  name: sandbox

AppName: techtrends

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: franroa/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 3111

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

livenessProbe:
  initialDelaySeconds: 10s
  periodSeconds: 5s
  path: /healthz
  port: 3111
readinessProbe:
  initialDelaySeconds: 10s
  periodSeconds: 5s
  path: /healthz
  port: 3111
